### ISSUE TITLE
download_media not raised FloodWait error

### ISSUE THREAD

**Issue by keklick1337** [pyrogram/pyrogram#1191]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

i'll tried to catch FloodWait exception from download_media function, and i can't do it. Why?

### Steps to reproduce

0. Login into telegram account
1. try to download parallel more than 1000 files
2. try to catch exception in download_media
3. catch nothing 

### Code example

```python
try:
    file = await app.download_media(msgobj, file_name=_filename, in_memory=False, progress=downloadCallback, progress_args=(_filename,))
except Exception as E:
    print(f'Exception raised {E}')
```

### Logs

```shell
Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 861, in get_file
    exported_auth = await self.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
```

**Comment by delivrance** [comment]
This has been addressed in the latest version by limiting concurrent transfers.

**Comment by keklick1337** [comment]
@delivrance how to catch FloodWait exception?

**Comment by fivepe** [comment]
> This has been addressed in the latest version by limiting concurrent transfers.

I am using the latest version, but it still appears Waiting for xxx seconds before continuing (required by "auth.ExportAuthorization") when use download_media()，max_concurrent_transmissions uses the default value
