### ISSUE TITLE
Downloads that raise a flood wait error will stop

### ISSUE THREAD

**Issue by delivrance** [pyrogram/pyrogram#262]
It may happen that sometimes downloads will trigger a flood wait error, but currently Pyrogram is not handling them as it should and quits the download thread instead by retuning `None`, logging the error and deleting anything downloaded so far. It would be nice to have it wait and retry automatically instead.

**Comment by delivrance** [comment]
Fixed, since a global `sleep_threshold` with automatic sleeping was added.

**Comment by ak2k** [comment]
Is anything special required to benefit from this? I'm still seeing the originally described issue.
