### ISSUE TITLE
message.download() raise  400 FILE_REFERENCE_EMPTY

### ISSUE THREAD

**Issue by ahmadly** [pyrogram/pyrogram#315]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
When I want to do download a file, I always get `FILE_REFERENCE_EMPTY` error. for example:
```python
client = Client(
                telegram_session_string,
                telegram_api_id,
                telegram_api_hash,
            )
with client:
    for message in client.iter_history('channel'):
        if message.empty or message.mentioned:
            continue

        if message.media:
                file = message.download()

```
unfortunately, I can't find anything in the error reference page [https://docs.pyrogram.org/api/errors#badrequest](https://docs.pyrogram.org/api/errors#badrequest)

## Traceback
```
[2019-09-14 17:32:28,190: DEBUG/ForkPoolWorker-2] PingThread started
[2019-09-14 17:32:28,190: INFO/ForkPoolWorker-2] Session initialized: Layer 102
[2019-09-14 17:32:28,191: INFO/ForkPoolWorker-2] Device: CPython 3.7.4 - Pyrogram 0.15.1
[2019-09-14 17:32:28,191: INFO/ForkPoolWorker-2] System: Darwin 18.7.0 (EN)
[2019-09-14 17:32:28,191: DEBUG/ForkPoolWorker-2] Session started
[2019-09-14 17:32:28,534: DEBUG/ForkPoolWorker-2] {
    "_": "Message",
    "msg_id": 6736580390664272897,
    "seq_no": 5,
    "length": 140,
    "body": {
        "_": "types.RpcResult",
        "req_msg_id": 6736580389837039616,
        "result": {
            "_": "types.auth.Authorization",
            "user": {
                "_": "types.User",
                "id": 74509408,
                "is_self": true,
                "contact": false,
                "mutual_contact": false,
                "deleted": false,
                "bot": false,
                "bot_chat_history": false,
                "bot_nochats": false,
                "verified": false,
                "restricted": false,
                "min": false,
                "bot_inline_geo": false,
                "support": false,
                "scam": false,
                "access_hash": *,
                "first_name": "*",
                "last_name": "*",
                "username": "*",
                "phone": "*",
                "photo": {
                    "_": "types.UserProfilePhoto",
                    "photo_id": *,
                    "photo_small": {
                        "_": "types.FileLocationToBeDeprecated",
                        "volume_id": 455205387,
                        "local_id": 399324
                    },
                    "photo_big": {
                        "_": "types.FileLocationToBeDeprecated",
                        "volume_id": 455205387,
                        "local_id": 399326
                    },
                    "dc_id": 4
                },
                "status": {
                    "_": "types.UserStatusOffline",
                    "was_online": 1568482250
                }
            }
        }
    }
}
[2019-09-14 17:32:28,836: DEBUG/ForkPoolWorker-2] {
    "_": "Message",
    "msg_id": 6736580392068740097,
    "seq_no": 7,
    "length": 44,
    "body": {
        "_": "types.RpcResult",
        "req_msg_id": 6736580391311489024,
        "result": {
            "_": "types.RpcError",
            "error_code": 400,
            "error_message": "FILE_REFERENCE_EXPIRED"
        }
    }
}
[2019-09-14 17:32:28,846: ERROR/ForkPoolWorker-2] [400 Bad Request]: [400 FILE_REFERENCE_EXPIRED] (caused by "upload.GetFile")
Traceback (most recent call last):
  File "/Users/ahmad/Projects/self/content_hub/venv/lib/python3.7/site-packages/pyrogram/client/client.py", line 1539, in get_file
    limit=limit
  File "/Users/ahmad/Projects/self/content_hub/venv/lib/python3.7/site-packages/pyrogram/session/session.py", line 437, in send
    return self._send(data, timeout=timeout)
  File "/Users/ahmad/Projects/self/content_hub/venv/lib/python3.7/site-packages/pyrogram/session/session.py", line 424, in _send
    RPCError.raise_it(result, type(data))
  File "/Users/ahmad/Projects/self/content_hub/venv/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 73, in raise_it
    is_unknown=True)
pyrogram.errors.exceptions.bad_request_400.BadRequest: [400 Bad Request]: [400 FILE_REFERENCE_EXPIRED] (caused by "upload.GetFile")
```

**Comment by delivrance** [comment]
Thanks for the report. This is a known new issue that is affecting user accounts only (bot accounts are currently working fine).

As hinted already in this [FAQ](https://docs.pyrogram.org/faq#can-i-use-bot-api-s-file-ids-in-pyrogram), Telegram suddenly decided to force require file references every time you want to access media and the error is due to Pyrogram always passing empty file references, which used to work until lately.

This means media can now be accessed only while messages exist, as file references are supposed to expire anytime and the only way to refresh them is to get the original messages again.

This requires some reasoning on how to proceed. While downloads can be fixed fairly easily by exposing file references, file ids are probably going to be changed.

**Comment by khorammfar** [comment]
> 
> 
> Thanks for the report. This is a known new issue that is affecting user accounts only (bot accounts are currently working fine).
> 
> As hinted already in this [FAQ](https://docs.pyrogram.org/faq#can-i-use-bot-api-s-file-ids-in-pyrogram), Telegram suddenly decided to force require file references every time you want to access media and the error is due to Pyrogram always passing empty file references, which used to work until lately.
> 
> This means media can now be accessed only while messages exist, as file references are supposed to expire anytime and the only way to refresh them is to get the original messages again.
> 
> This requires some reasoning on how to proceed. While downloads can be fixed fairly easily by exposing file references, file ids are probably going to be changed.

With these explanations you gave
  So how do we send or download a photo of the channel instead?

**Comment by pesaventofilippo** [comment]
I'm having the same issue, any updates?

**Comment by es3n1n** [comment]
@pesaventofilippo you will see commit, when dev will fix it ¯\_(ツ)_/¯

**Comment by delivrance** [comment]
Looks like Telegram decided to roll back some changes server side because the error, starting today, is gone without doing anything. I'm closing this issue for now and I'll re-open if needed.

**Comment by ehsanonline** [comment]
I'm having this problem too. started from today. please re-open!
```
[520 Unknown error]: {
    "_": "types.RpcError",
    "error_code": 400,
    "error_message": "FILE_REFERENCE_EMPTY"
}
```
pyrogram=0.14.1
python=3.6

**Comment by ColinTheShark** [comment]
> pyrogram=0.14.1

Update your Pyrogram first, please. There is 0.15.1 already and 0.16.x is in develop.

**Comment by dCosminn** [comment]
I'm running two clients/scripts. I'm getting the same issue on one of them, the other works fine.

`[520 Unknown error]: {
    "_": "telegram:RpcError",
    "error_code": 400,
    "error_message": "FILE_REFERENCE_EMPTY"
}
Traceback (most recent call last):
  File "D:\Programming\Python3.6\lib\site-packages\pyrogram\client\client.py", line 1563, in get_file
    limit=limit
  File "D:\Programming\Python3.6\lib\site-packages\pyrogram\session\session.py", line 420, in send
    return self._send(data, timeout=timeout)
  File "D:\Programming\Python3.6\lib\site-packages\pyrogram\session\session.py", line 407, in _send
    Error.raise_it(result, type(data))
  File "D:\Programming\Python3.6\lib\site-packages\pyrogram\api\errors\error.py", line 63, in raise_it
    raise UnknownError(x=rpc_error, query_type=query_type)
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
    "_": "telegram:RpcError",
    "error_code": 400,
    "error_message": "FILE_REFERENCE_EMPTY"`

**Comment by itshaadi** [comment]
it seems that this issue is caused by telegram's back-end, I'm also experiencing this and it's not consistent.
pyrogram 0.15.1
python 3.7.4

**Comment by KunoiSayami** [comment]
Should works now, guess is telegram back-end problem, not `pyorgram` problem.
`pyrogram` 0.15.1/0.14.0
`python` 3.7.4

**Comment by delivrance** [comment]
Issue fixed in https://github.com/pyrogram/pyrogram/commit/1cd94520bf136fcc69b632c3548b6135ae1257c2 and https://github.com/pyrogram/pyrogram/commit/92c1b48132783c31b2cdbdd33b576b6da7700f7c.

This is how it works now (users only, bot accounts are not strictly required to use file references yet): to correctly re-send, download, edit or forward as copy a media message, you must pass a valid and up to date `file_ref` you can get from a media object (audio, video, photo, document, ...).

The inevitable downside (because this is how Telegram wants it to work now) is that once a file reference expires (usually after 24h, but could happen anytime) you have to manually fetch the original message again with `get_messages` and the context (a pair of chat_id + message_id) in order to get a refreshed file reference.

**Comment by cesco327** [comment]
I have the same problem:
pyrogram.errors.rpc_error.UnknownError: [520 Unknown error]: [-503 Timeout] (caused by "upload.GetFile")
how can i fix?

**Comment by hughesjj** [comment]
I am still getting this issue on brand new images posted to a channel

**Comment by delivrance** [comment]
@hughesjj `FILE_REFERENCE_EMPTY` is documented and the error message tells you exactly what you need to do for it not to appear anymore.

**Comment by hughesjj** [comment]
> @hughesjj `FILE_REFERENCE_EMPTY` is documented and the error message tells you exactly what you need to do for it not to appear anymore.

Sorry, I'm referring to the above error by @cesco327.  I'll edit my post to correct that, but you're right in that a 503 timeout is not the same as the original topic.  I'll go ahead and look for another issue for that problem -- my best guess would be "retry if this happens" but I'm curious as to what underlying modalities may trigger this error.

**Comment by SantiiRepair** [comment]
Pyrogram 2.0.106 getting same bug

`Telegram says: [400 FILE_REFERENCE_EXPIRED] - The file id contains an expired file reference, you must obtain a valid one by fetching the message from the origin context (caused by "upload.GetFile")`

Throwed from `pyrogram.errors.exceptions.bad_request_400.FileReferenceExpired`

` if replied.audio:
                name = "Audio File"
                await msg.edit("➕ **__Downloading...__**")
                media = await user.download_media(
                    replied.audio,
                    block=False,
                    file_name=download_as,
                    progress=progress,
                )`

**Comment by jianchao123** [comment]
I called get_messages again, but it still reported an error，the code snippet is as follows：
`async def download_file(client, file_id, file_path, file_kind, from_channel_id, message_id) -> bool:
    # if os.path.exists(file_path):
    #     return True
    retry = False
    try:
        await client.download_media(file_id, file_name=file_path)
    except FileReferenceExpired:
        retry = True
    if retry:
        try:
            msg = await client.get_messages(from_channel_id, message_id)
            file_id = msg.video.file_id if file_kind == 'video' else msg.video.thumbs[0].file_id
            await client.download_media(file_id, file_name=file_path)
        except FileReferenceExpired:
            import traceback
            traceback.print_exc()
            return False
    return True`

**Comment by jianchao123** [comment]
@delivrance
