### ISSUE TITLE
client.download_media consistently fails for photos for _some_ messages -503 Timeout

### ISSUE THREAD

**Issue by ChrisRxyz** [pyrogram/pyrogram#664]
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Im using pyrogram to forward messages to another system, using a raw handler to process the messages and also download corresponding media (mostly images).
Im using the client.download_media method. This works for almost all messages but for some it just wont download the images and return None as a path. I could not figure out why it happens but identified some messages for which it consistently happens. 

I made a small testcase that fetches one of these messages from a channel and tries to download the media.

The message looks like this:

```
{
    "_": "Message",
    "message_id": 5869,
    "sender_chat": {
        "_": "Chat",
        "id": -1001133587448,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "Klondike (Crypto Rush) ⚠️",
        "username": "CryptoKlondike",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAATtJV9J10AAwIAAwjEyecW____ZkFiWLn_WDe_GwQAAR4E",
            "small_photo_unique_id": "AQADtJV9J10AA78bBAAB",
            "big_file_id": "AQADBAATtJV9J10AAwMAAwjEyecW____ZkFiWLn_WDfBGwQAAR4E",
            "big_photo_unique_id": "AQADtJV9J10AA8EbBAAB"
        },
        "dc_id": 4
    },
    "date": "2021-02-19 10:35:42",
    "chat": {
        "_": "Chat",
        "id": -1001133587448,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "Klondike (Crypto Rush) ⚠️",
        "username": "CryptoKlondike",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAATtJV9J10AAwIAAwjEyecW____ZkFiWLn_WDe_GwQAAR4E",
            "small_photo_unique_id": "AQADtJV9J10AA78bBAAB",
            "big_file_id": "AQADBAATtJV9J10AAwMAAwjEyecW____ZkFiWLn_WDfBGwQAAR4E",
            "big_photo_unique_id": "AQADtJV9J10AA8EbBAAB"
        },
        "dc_id": 4
    },
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "media": true,
    "author_signature": "Robert Mercer 🔥",
    "caption_entities": [
        {
            "_": "MessageEntity",
            "type": "bold",
            "offset": 0,
            "length": 15
        },
        {
            "_": "MessageEntity",
            "type": "bold",
            "offset": 36,
            "length": 7
        },
        {
            "_": "MessageEntity",
            "type": "bold",
            "offset": 44,
            "length": 4
        },
        {
            "_": "MessageEntity",
            "type": "bold",
            "offset": 114,
            "length": 6
        }
    ],
    "photo": {
        "_": "Photo",
        "file_id": "AgACAgQAAx0CQ5Er-AACFu1gcwc0j8RpzQcWvVFQOom1Zz4iLwACtbgxG8ydgVEdyclzkLTMRe9xGypdAAMBAAMCAAN5AAPDxAIAAR4E",
        "file_unique_id": "AQAD73EbKl0AA8PEAgAB",
        "width": 1280,
        "height": 782,
        "file_size": 83252,
        "date": "2021-02-19 10:35:42",
        "thumbs": [
            {
                "_": "Thumbnail",
                "file_id": "AgACAgQAAx0CQ5Er-AACFu1gcwc0j8RpzQcWvVFQOom1Zz4iLwACtbgxG8ydgVEdyclzkLTMRe9xGypdAAMBAAMCAANtAAPExAIAAR4E",
                "file_unique_id": "AQAD73EbKl0AA8TEAgAB",
                "width": 320,
                "height": 196,
                "file_size": 14143
            },
            {
                "_": "Thumbnail",
                "file_id": "AgACAgQAAx0CQ5Er-AACFu1gcwc0j8RpzQcWvVFQOom1Zz4iLwACtbgxG8ydgVEdyclzkLTMRe9xGypdAAMBAAMCAAN4AAPFxAIAAR4E",
                "file_unique_id": "AQAD73EbKl0AA8XEAgAB",
                "width": 800,
                "height": 489,
                "file_size": 52220
            }
        ]
    },
    "caption": "🐝 BTC UPDATE\n\nWe just stick to our initial plan and holding a big bag of Bitcoin. The target is still the same - $60000.",
    "views": 14444,
    "outgoing": false
}

```

## Steps to Reproduce
This is my test code to fetch the message and download the media photo:

```

from pyrogram import Client, filters, idle
from pyrogram.handlers import MessageHandler
import time
import logging

client = Client(
    '',
    api_id='',
    api_hash=''
)

def handle_new_impl(client:Client, message):
    print(f"New message: {str(message)}")


def handle_new(client, message):
    return handle_new_impl(client, message)

def main():
    # Pyrogram setup
    client.add_handler(MessageHandler(handle_new)) 
    client.start()
    m = client.get_messages(-1001133587448, 5869, replies=0)
    path = None
    print(f'Found message: {str(m)}')
    path = client.download_media(m, file_name="test1.jpg", block=False)
    print(f'Downloaded to: {str(path)}')
    idle()
    client.stop()

if __name__ == '__main__':
    main()

```

Ive tried with block=False and block=True
When using block=True I get a getFile timeout error from the network code. When I use block=False I just get None as a path.
Ive also tried using the file reference, adding a filename, basically trying all the different parameters of downloade_media with no luck. Its not a huge image either. It works when I try to download the same image if posted in another channel for example.

## Traceback
This is the traceback for using block=True

```
[520 Unknown error]: [-503 Timeout] (caused by "upload.GetFile")
Traceback (most recent call last):
  File "/home/workspace/telegram/github_pyrogram/pyrogram/client.py", line 939, in get_file
    r = await session.send(
  File "/home/workspace/telegram/github_pyrogram/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/workspace/telegram/github_pyrogram/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/workspace/telegram/github_pyrogram/pyrogram/errors/rpc_error.py", line 59, in raise_it
    raise UnknownError(
pyrogram.errors.rpc_error.UnknownError: [520 Unknown error]: [-503 Timeout] (caused by "upload.GetFile")
Downloaded to: None

```
Just for the sake of reproducing above code, the channel I used it on is this https://t.me/CryptoKlondike (remove it if links are not allowed plz) Its a very big channel, maybe it has something to do with it. But it does happen with other channels aswell.

Any pointers on how to fix this would be much appreciated!

**Comment by AndrielFR** [comment]
Use the message media itself instead of the full message, like:
```py
path = client.download_media(m.photo, file_name="test1.jpg", block=False)
```

**Comment by delivrance** [comment]
`-503 Timeout` is a server error and can happen. However, this is currently not handled properly by Pyrogram.

**Comment by AndrielFR** [comment]
> `-503 Timeout` is a server error and can happen. However, this is currently not handled properly by Pyrogram.

Oh, understand.

**Comment by ChrisRxyz** [comment]
> `-503 Timeout` is a server error and can happen. However, this is currently not handled properly by Pyrogram.

I know this can happen _sometimes_. But in this case it is not a random occasion. This happens for the above specified message _every_ time.  And I ran the code from different networks, pcs, and well connected dedicated servers. So its not like its an issue with a bad connection.  
I really dont know what to do anymore to get this to work. If I forward the same message to another channel and then download the image/media its works just fine. But not on the original message in the original channel...

Also, as I mentioned, block=False doesnt work either, but without the 503 Error.

**Comment by delivrance** [comment]
> So its not like its an issue with a bad connection.
It might be, probably at the server side.

The server is struggling to retrieve the file and timeouts.
Again, there's nothing to do except making Pyrogram handle those server side 503 timeout errors and retry again automatically.

**Comment by ChrisRxyz** [comment]
Is it normal that I run above code 100 times and get the timeout 100 times? Is there nothing to make this work somehow? I even ran this in a loop.
Also,  I usually I dont fetch old messages with get_messages (if that could have something to do with it), but just process the newly incoming messages and just can not download the photo. It works on every other telegram client (mobile, browser, native win app) so I dont understand how it could be a server issue.

**Comment by delivrance** [comment]
I pushed a new branch, `handle-503-timeout`. You can install from it and see how it goes, install with `pip3 install -U https://github.com/pyrogram/pyrogram/archive/handle-503-timeout.zip`.

The change allows Pyrogram to retry again automatically on these new errors up to some times before giving up and raising the exception, this is to hope the server side issue solves by itself meanwhile.

**Comment by ChrisRxyz** [comment]
Unfortunately this did not fix it for me. I now get the following error - which is similar - its just re-trying more often.

```
[5] Retrying "upload.GetFile" due to Timeout('[-503 Timeout]: Telegram is having internal problems. Please try again later. (caused by "upload.GetFile")')
[-503 Timeout]: Telegram is having internal problems. Please try again later. (caused by "upload.GetFile")
Traceback (most recent call last):
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/client.py", line 939, in get_file
    r = await session.send(
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 444, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/ch/workspace/crypto/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 444, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 444, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 437, in send
    raise e from None
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/workspace/telegram/pyrogram2_2/venv/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.service_unavailable_503.Timeout: [-503 Timeout]: Telegram is having internal problems. Please try again later. (caused by "upload.GetFile")
```
Im always trying with the above mentioned message which a photo attachment. Again, only doesnt work with messages from specific channels.

**Comment by delivrance** [comment]
I can imagine Telegram limiting media downloads for big channels, just a guess. Remember that all 5xx errors are server errors, clients like Pyrogram can't do much about them except trying again.

**Comment by ChrisRxyz** [comment]
I just wonder then how telegram clients can display these messages and images. Surely they have to download them somehow, too. I can browse the same message and download the same images just fine on the other clients.

**Comment by delivrance** [comment]
Apparently a new schema has been published lately and it changed some photos' internals.

**Comment by ChrisRxyz** [comment]
That could definitely explain it. The code used to work just fine until some 1-2 months ago.

**Comment by delivrance** [comment]
To @ChrisRxyz and others who are getting this error: I added support for media servers which could help solve this issue. You can install from master to try and see if you still get it, https://docs.pyrogram.org/intro/install#bleeding-edge.

**Comment by ChrisRxyz** [comment]
@delivrance Thanks, that probably solved the issue. The downloads now work as expected.

**Comment by nikitanix1** [comment]
Still getting this error. Pyrogram 1.2.9. I'm trying to download videos from message via message.download(file_name=filename).

pyrogram.errors.rpc_error.UnknownError: [520 Unknown error]: [-503 Timeout] (caused by "upload.GetFile")

**Comment by ChrisRxyz** [comment]
This error was resolved, I one of the updates of the media servers a few versions ago. 

Unfortunately the issue is back again. I cant download media files (mostly photos) from some specific channels.
The steps to reproduce are the same as in my OP.

One of the channels where this consistently fails is for example: https://t.me/CryptoKlondike.

Maybe something changed with the media servers again? Hopefully this can be fixed more easily now as the problem has been fixed once in the past before 🤞

**Comment by delivrance** [comment]
I don't think there's anything else to be done at the client side as this was and still remains a server error in the first place.

**Comment by delivrance** [comment]
Anyway, there was a couple of layer changes lately and installing from the master branch again could help as newer schemas mean telling telegram you are using an updated client.

**Comment by antomarsi** [comment]
This error is still happens on 1.2.9:

it happens when running download_media of a message, but after testing, it happens only in some channels.

**Comment by ChrisRxyz** [comment]
6 months later, still having the same issue.

Please do look into this. This only happens for big channels >5k members. There must be a way to get this working. I´ll even be happy with some workaround...

If I forward the same message to a small group or private chat, pyrogram can download the media just find with the same code.

**Comment by AduchiMergen** [comment]
patch from JohnSmith09512 fixed issue for me

**Comment by AduchiMergen** [comment]
problem in this case:

some times server don't send response if offset more then file size (i think some file storages don't support this behavior)

so fix in one line: need change condition for break loop to len(chunk) < limit
